### PR TITLE
Improve auth

### PR DESCRIPTION
**Pull request by sooox-cc**
- /login
- /register
- /logout
- 404 page
- a whole lot of session stuff

### CODE REVIEW

**Comment by sooox-cc** [comment]
@SleepingAmi pleaseeeee

**Review by SleepingAmi — APPROVED** [review]
mb

**Comment by sooox-cc** [comment]
hmm dont merge yet i think i just found something

**Comment by sooox-cc** [comment]
forget that im just dumb ^
i found something in the code i hadn't pushed yet

**Pull request merged**
